# Analysis of Repressions Against Cultural Figures

This notebook analyzes a dataset of **cultural workers who were sentenced to imprisonment** in prisons or penal colonies.

The goal is to clean the dataset, extract the year of each sentence, count how many people were sentenced in each year, and visualize the results.

### 1. Loading the data

The notebook begins by importing pandas and loading the dataset from repressions_culture.csv.

In [1]:
import pandas as pd

In [2]:
Cultural figures sentenced to serve their sentences in prisons and penal colonies
df = pd.read_csv('repressions_culture.csv')

In [3]:
df

,"Дзеячы культуры, асуджаныя да адбывання пакарання ў турмах і калоніях",Unnamed: 1,Unnamed: 2
0,"Імя, прозвішча",Культурніцкая дзейнасць,Прысуд
1,Аліневіч Ігар,"Пісьменнік, актывіст анархістскага руху",Асуджаны 22 снежня 2021 года да 20 гадоў пазба...
2,Алфёрава Нэлі,"Рамесніца, мастачка і літаратарка",У чэрвені 2024 года прымусова накіраваная на п...
3,Аляксандраў Андрэй,"Паэт, журналіст, медыяменеджэр",Асуджаны 6 кастрычніка 2022 года да 14 гадоў п...
4,Арэшка Вячаслаў,"Архівіст, культуразнаўца, гісторык, грамадскі ...",Асуджаны 5 студзеня 2023 года да 13 гадоў пазб...
...,...,...,...
91,Колас Зміцер,"Перакладчык, літаратуразнаўца, уладальнік выда...",Затрыманы 17 лютага 2026 года. Знаходзіцца ў С...
92,Ларычаў Алег,"Арт-менеджэр, стрыт-арт мастак",Затрыманы ў снежні 2025 года. Знаходзіцца ў СІ...
93,Малашэнкаў Сямён,Арт-менеджэр,Затрыманы ў лістападзе 2025 года
94,Салаш Сяргей,"Арт-менеджэр, грамадскі дзеяч, сузаснавальнік ...",Затрыманы 12 лістапада 2025 года
95,Чумакоў Алесь,Даследчык і рэстаўратар традыцыйных музычных і...,Затрыманы 8 снежня 2025. Знаходзіцца ў СІЗА-1

### 2. Cleaning the dataset

The first row of the CSV contains the actual column names, so I use that row as the header and remove it from the data.

This makes the dataframe easier to work with because each column now has a meaningful name.

In [4]:
# Use first row as column names
df.columns = df.iloc[0]

# Remove the row that became the header
df = df.iloc[1:].reset_index(drop=True)

In [5]:
df

,"Імя, прозвішча",Культурніцкая дзейнасць,Прысуд
0,Аліневіч Ігар,"Пісьменнік, актывіст анархістскага руху",Асуджаны 22 снежня 2021 года да 20 гадоў пазба...
1,Алфёрава Нэлі,"Рамесніца, мастачка і літаратарка",У чэрвені 2024 года прымусова накіраваная на п...
2,Аляксандраў Андрэй,"Паэт, журналіст, медыяменеджэр",Асуджаны 6 кастрычніка 2022 года да 14 гадоў п...
3,Арэшка Вячаслаў,"Архівіст, культуразнаўца, гісторык, грамадскі ...",Асуджаны 5 студзеня 2023 года да 13 гадоў пазб...
4,Бабарыка Эдуард,Кіраўнік краўдфандынгавых пляцовак падтрымкі к...,Асуджаны 5 ліпеня 2023 года да 8 гадоў пазбаўл...
...,...,...,...
90,Колас Зміцер,"Перакладчык, літаратуразнаўца, уладальнік выда...",Затрыманы 17 лютага 2026 года. Знаходзіцца ў С...
91,Ларычаў Алег,"Арт-менеджэр, стрыт-арт мастак",Затрыманы ў снежні 2025 года. Знаходзіцца ў СІ...
92,Малашэнкаў Сямён,Арт-менеджэр,Затрыманы ў лістападзе 2025 года
93,Салаш Сяргей,"Арт-менеджэр, грамадскі дзеяч, сузаснавальнік ...",Затрыманы 12 лістапада 2025 года
94,Чумакоў Алесь,Даследчык і рэстаўратар традыцыйных музычных і...,Затрыманы 8 снежня 2025. Знаходзіцца ў СІЗА-1

### 3. Extracting sentencing years

The column Прысуд contains text descriptions of each sentence.
I use a regular expression to extract the first four-digit year from each sentence and save it in a new column called Год прысуду.

In [8]:
df['Прысуд']

0     Асуджаны 22 снежня 2021 года да 20 гадоў пазба...
1     У чэрвені 2024 года прымусова накіраваная на п...
2     Асуджаны 6 кастрычніка 2022 года да 14 гадоў п...
3     Асуджаны 5 студзеня 2023 года да 13 гадоў пазб...
4     Асуджаны 5 ліпеня 2023 года да 8 гадоў пазбаўл...
                            ...
90    Затрыманы 17 лютага 2026 года. Знаходзіцца ў С...
91    Затрыманы ў снежні 2025 года. Знаходзіцца ў СІ...
92                     Затрыманы ў лістападзе 2025 года
93                     Затрыманы 12 лістапада 2025 года
94        Затрыманы 8 снежня 2025. Знаходзіцца ў СІЗА-1
Name: Прысуд, Length: 95, dtype: str

In [6]:
# Extract first 4-digit year from the sentence
df['Год прысуду'] = df['Прысуд'].str.extract(r'(\d{4})')

In [7]:
df['Год прысуду']

0     2021
1     2024
2     2022
3     2023
4     2023
      ...
90    2026
91    2025
92    2025
93    2025
94    2025
Name: Год прысуду, Length: 95, dtype: str

### 4. Counting sentences by year

After extracting the years, I count **how many people were sentenced** in each year.

The result is a new dataframe called **year_counts**, with two columns:

- year: the sentencing year
- count: the number of people sentenced that year

In [9]:
year_counts = (
    df['Год прысуду']
    .value_counts()
    .sort_index()
    .reset_index()
)

year_counts.columns = ['year', 'count']

### 5. Visualizing the results

Finally, I use Altair to create a bar chart showing the number of sentenced cultural figures by year.

The chart makes it easier to see how sentencing patterns changed over time.

In [10]:
import altair as alt

chart = (
    alt.Chart(year_counts)
    .mark_bar()
    .encode(
        x=alt.X('year:O', title='Year'),
        y=alt.Y('count:Q', title='Number of people'),
        tooltip=['year', 'count']
    )
    .properties(
        title='People sentenced by year',
        width=600,
        height=400
    )
)

chart

alt.Chart(...)